language: python

python:
  - '3.6'


cache:
  pip: true
  directories:
  - docker_images

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - docker load -i docker_images/images.tar || true

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

install:
  - pip install -r requirements.txt .

before_script:
  - docker-compose -f docker/mysql/docker-compose.yml up --build -d
  - docker-compose -f docker/pgsql/docker-compose.yml up --build -d

script:
    - until $(curl -qs localhost:8182 > /dev/null && curl -qs localhost:8181 > /dev/null); do sleep 3; done && pytest

after_script:
  - docker-compose -f docker/mysql/docker-compose.yml down
  - docker-compose -f docker/pgsql/docker-compose.yml down

after_success:
  - codecov # submit coverage
