language: python
python:
  - '3.6'
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install .
before_script:
  - docker-compose -f docker/mysql/docker-compose.yml up --build -d
script:
    - pytest -s -v
after_script:
  - docker-compose down
after_success:
  - codecov # submit coverage